conda_forge_output_validation: true
build_with_mambabuild: true
remote_ci_setup: "conda-forge-ci-setup=3"
bot:
  automerge: true
  check_solvable: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
